services:
  - type: web
    name: malvryx-bot
    env: python
    buildCommand: |
      curl -fsSL https://pyenv.run | bash
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      pyenv install 3.11.9
      pyenv global 3.11.9
      pip install -r requirements.txt
    startCommand: python3.11 bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: PORT
        value: 5000
